Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -27,9 +27,16 @@ jobs:
       - name: Run and collect coverage
         run: | 
           cd golden-compare
-          coverage run testfolders.py
+          coverage run -m unittest discover
           coverage html
           coverage report
+          COVERAGE=$(coverage report | awk 'END{print $NF}' | sed 's/[^0-9]*//g')
+          if [ "$COVERAGE" -lt 100 ]; then
+              echo "Coverage is less than 100%. Failing the build..."
+              exit 1
+          else
+              echo "Coverage is greater than or equal to 100%."
+          fi
     
       - name: Upload coverage
         uses: actions/upload-artifact@v2
